name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: Patch Earthfile
        run: sed -i -E 's/(.*)(BUILD \+test-stack)/\1# \2/g' Earthfile
      - name: Run build
        run: earthly +all
